- hosts: all
  gather_facts: false
  tasks:
    #- slurp:
    #    src: "/tmp/id"
    #  register: system_id

    - group_by:
        key: "{{ system_id }}"
      when: "system_id is defined"

    - group_by:
        key: "insights_hosts"
      when: "system_id is defined"

- hosts: host1-7571049d-1b94-47e0-b873-1d2911083467:host2-8f07b7a5-5a7b-46a7-bdc2-172824b596d6
  tasks:
    - debug:
        msg: "hello world from {{ inventory_hostname }} with myvar={{ myvar }}"

- hosts: insights_hosts
  tasks:
    - debug:
        msg: "hello world from {{ inventory_hostname }} with myvar={{ myvar }}"
