- hosts: all
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: '{{ lookup("env", "ANSIBLE_NET_SSH_KEYFILE")  }}'
  tasks:
    - debug:
        msg: "Key file is {{ ansible_ssh_private_key_file }}"

    - ping:
