- hosts: localhost
  tasks:
    - include_vars: "roles/chicken/defaults/main.yml"
    - include_role:
        name: "egg"
      vars:
        egg_var: "{{ chicken_var }}"
    - include_role:
        name: "chicken"
        
