# passes a variable, test_foo_a, defined in roles/test/defaults/main.yml to itself
#
- hosts: localhost
  gather_facts: false
  roles:
    - role: test
      test_foo_b: "{{ test_foo_a }}"

# Variable being debugged is not defined
- hosts: localhost
  gather_facts: false
  roles:
    - role: test

- hosts: localhost
  gather_facts: false
  tasks:
    - debug: msg="Role defined in defaults/main.yml DOES NOT live on past role invocation across plays ... {{ test_foo_a|default('variable is dead!') }}"

# Variables scope/life after role invocation
# Variable does not live on!
- hosts: localhost
  gather_facts: false
  roles:
    - role: test
  tasks:
    - debug: msg="Role defined in defaults/main.yml DOES live on past role invocation ... {{ test_foo_a|default('variable is dead!') }}"
