- name: "Demonstrate that we can reference a roles/test/defaults/main.yml variable during a role invocation"
  hosts: localhost
  gather_facts: false
  roles:
    - role: test
      test_foo_b: "{{ test_foo_a }} <--- from 'test_foo_a' roles/test/defaults/main.yml"

- name: "Demonstrates that variables defined in roles/test/defaults/main.yml don't live on across plays"
  hosts: localhost
  gather_facts: false
  tasks:
    - debug: msg="Role defined in defaults/main.yml DOES NOT live on past role invocation across plays ... {{ test_foo_a|default('variable is dead!') }}"

- name: "Use set_fact to extend the life of a role variable"
  hosts: localhost
  gather_facts: false
  roles:
    - role: test
  tasks:
    - name: "Save roles/test/defaults/main.yml test_foo_a => foo_a"
      set_fact:
        foo_a: "{{ test_foo_a }}"

- name: "Show that a set_fact fact can live on across a play"
  hosts: localhost
  gather_facts: false
  tasks:
    - debug: msg="foo_a should be hello - {{ foo_a }}"


- name: "Call set_fact in a role, then access that variable in a tasks, after the role is called"
  hosts: localhost
  gather_facts: false
  roles:
    - role: set_fact_inside
  tasks:
    - debug:
        msg: "set_fact_inside role calls set_fact on a previously non-existant variable, that variable is set_fact_inside_my_var='foobar' and the value is: {{ set_fact_inside_my_var }}"

- name: "Facts set for the first time in roles live across plays"
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "set_fact_inside role calls set_fact on a previously non-existant variable, that variable is set_fact_inside_my_var='foobar' and the value is: {{ set_fact_inside_my_var }}"

